apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  labels:
    version: 1.0.0
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    env:
      - name: SERVICE_VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['version']
  restartPolicy: Always